import jmri
class setStartup(jmri.jmrit.automat.AbstractAutomaton) :
   def init(self):
      return
   
   def handle(self):
      turnouts.provideTurnout("CT2").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT3").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT4").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT5").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT6").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT7").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT8").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT9").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT10").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT11").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT12").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT14").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT15").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT16").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT17").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT18").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT19").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT22").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT23").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT24").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT29").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT30").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT31").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT32").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT33").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT34").setState(CLOSED)
      self.waitMsec(1000)
      turnouts.provideTurnout("CT35").setState(CLOSED)
      self.waitMsec(1000)
      return false              # all done, don't repeat again

setStartup().start()          # create one of these, and start it running 
